name: 'Build Writerside docs'
description: 'Build Writerside documentation artifacts'
author: 'writerside <writerside@jetbrains.com>'

runs:
    using: 'docker'
    image: 'registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.984'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - run: |
            set -e
            /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $PRODUCT -output-dir artifacts/ || true
            echo "Test existing of $ARTIFACT artifact"
            test -e artifacts/$ARTIFACT
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
             name: artifact
             path: artifacts/${{ env.ARTIFACT }}
             retention-days: 7
branding:
    icon: 'book-open'
    color: 'purple'
