name: Build Writerside docs
description: Build Writerside documentation artifacts
author: writerside <writerside@jetbrains.com>
branding:
  icon: book-open
  color: purple
  
runs:
  using: 'docker'
  image: 'registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.984' 
  entrypoint: 'build.sh'
