name: Build Writerside docs
description: Build Writerside documentation artifacts
author: writerside <writerside@jetbrains.com>
branding:
  icon: book-open
  color: purple
  
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          set -e
          /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . --runner github -product $PRODUCT -output-dir artifacts/ || true
          echo "Test existing of $ARTIFACT artifact"
          test -e artifacts/$ARTIFACT
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifacts/${{ env.ARTIFACT }}
          retention-days: 7
          
