name: 'Build Writerside docs'
description: 'Build Writerside documentation artifacts'
author: 'writerside <writerside@jetbrains.com>'
branding:
    icon: 'book-open'
    color: 'purple'

runs:
    using: 'docker'
    image: 'registry.jetbrains.team/p/writerside/builder/writerside-builder:2.1.984'
    steps:
        - run: |
            set -e
            /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $PRODUCT -output-dir artifacts/ || true
            echo "Test existing of $ARTIFACT artifact"
            test -e artifacts/$ARTIFACT
